// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/index.qtpl:1
package views

//line views/index.qtpl:1
import "github.com/lemon-mint/gopkg.eu.org/types"

//line views/index.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/index.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/index.qtpl:4
type Module = types.Module

//line views/index.qtpl:7
func StreamIndex(qw422016 *qt422016.Writer, Modules []*Module) {
//line views/index.qtpl:7
	qw422016.N().S(`<!DOCTYPE html>
`)
//line views/index.qtpl:8
	qw422016.N().S(`<html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>gopkg.eu.org Module Index</title><meta name="og:title" content="gopkg.eu.org Module Index"><meta name="og:description" content="A Module index for Go Modules hosted on gopkg.eu.org"><meta name="description" content="A Module index for Go Modules hosted on gopkg.eu.org"><link rel="stylesheet" href="/_static/main.css"></head><body><h1>gopkg.eu.org Module Index</h1><br/><div class="box"><ul>`)
//line views/index.qtpl:25
	for _, p := range Modules {
//line views/index.qtpl:25
		qw422016.N().S(`<li><a href="/`)
//line views/index.qtpl:27
		qw422016.E().S(p.Path)
//line views/index.qtpl:27
		qw422016.N().S(`">`)
//line views/index.qtpl:27
		qw422016.E().S(p.Root)
//line views/index.qtpl:27
		qw422016.N().S(`</a></li>`)
//line views/index.qtpl:29
	}
//line views/index.qtpl:29
	qw422016.N().S(`</ul></div></body></html>`)
//line views/index.qtpl:34
	qw422016.N().S(`
`)
//line views/index.qtpl:35
}

//line views/index.qtpl:35
func WriteIndex(qq422016 qtio422016.Writer, Modules []*Module) {
//line views/index.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/index.qtpl:35
	StreamIndex(qw422016, Modules)
//line views/index.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line views/index.qtpl:35
}

//line views/index.qtpl:35
func Index(Modules []*Module) string {
//line views/index.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line views/index.qtpl:35
	WriteIndex(qb422016, Modules)
//line views/index.qtpl:35
	qs422016 := string(qb422016.B)
//line views/index.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line views/index.qtpl:35
	return qs422016
//line views/index.qtpl:35
}
