// Code generated by qtc from "mod.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/mod.qtpl:1
package views

//line views/mod.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/mod.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/mod.qtpl:1
func StreamMod(qw422016 *qt422016.Writer, Root, VCS, RepoURL, Description string) {
//line views/mod.qtpl:1
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>`)
//line views/mod.qtpl:7
	qw422016.E().S(Root)
//line views/mod.qtpl:7
	qw422016.N().S(`</title>
    <meta name="og:title" content="`)
//line views/mod.qtpl:8
	qw422016.E().S(Root)
//line views/mod.qtpl:8
	qw422016.N().S(`">
    <meta name="og:description" content="`)
//line views/mod.qtpl:9
	qw422016.E().S(Description)
//line views/mod.qtpl:9
	qw422016.N().S(`">
    <meta name="description" content="`)
//line views/mod.qtpl:10
	qw422016.E().S(Description)
//line views/mod.qtpl:10
	qw422016.N().S(`">
    <meta name="go-import" content="`)
//line views/mod.qtpl:11
	qw422016.E().S(Root)
//line views/mod.qtpl:11
	qw422016.N().S(` `)
//line views/mod.qtpl:11
	qw422016.E().S(VCS)
//line views/mod.qtpl:11
	qw422016.N().S(` `)
//line views/mod.qtpl:11
	qw422016.E().S(RepoURL)
//line views/mod.qtpl:11
	qw422016.N().S(`">
    <link rel="stylesheet" href="/_static/main.css">
</head>
<body>
    <div class="box">
        <h1>`)
//line views/mod.qtpl:16
	qw422016.E().S(Root)
//line views/mod.qtpl:16
	qw422016.N().S(`</h1>
        <hr/>
        <p>Documentation for this module is available at <a href="https://pkg.go.dev/`)
//line views/mod.qtpl:18
	qw422016.E().S(Root)
//line views/mod.qtpl:18
	qw422016.N().S(`">`)
//line views/mod.qtpl:18
	qw422016.E().S(Root)
//line views/mod.qtpl:18
	qw422016.N().S(`</a></p>

        <p>`)
//line views/mod.qtpl:20
	qw422016.E().S(Description)
//line views/mod.qtpl:20
	qw422016.N().S(`</p>
    </div>
</body>
</html>
`)
//line views/mod.qtpl:24
}

//line views/mod.qtpl:24
func WriteMod(qq422016 qtio422016.Writer, Root, VCS, RepoURL, Description string) {
//line views/mod.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/mod.qtpl:24
	StreamMod(qw422016, Root, VCS, RepoURL, Description)
//line views/mod.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line views/mod.qtpl:24
}

//line views/mod.qtpl:24
func Mod(Root, VCS, RepoURL, Description string) string {
//line views/mod.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line views/mod.qtpl:24
	WriteMod(qb422016, Root, VCS, RepoURL, Description)
//line views/mod.qtpl:24
	qs422016 := string(qb422016.B)
//line views/mod.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line views/mod.qtpl:24
	return qs422016
//line views/mod.qtpl:24
}
